services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=demo
      - DB_PORT=3306
      - JWT_SECRET=your_jwt_secret_key_here_change_it
      - JWT_EXPIRES_IN=1d
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./flyway/sql:/docker-entrypoint-initdb.d
  flyway:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/demo
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      - db
volumes:
  mysql_data:
