services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - DB_HOST=db
      - DB_NAME=demo
      - DB_PORT=27017

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: demo
    ports:
      - "${DB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-migrate:
    image: node:22-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install migrate-mongo && npm run migrate"
    environment:
      - DB_HOST=db
      - DB_NAME=demo
    depends_on:
      - db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
volumes:
  mongodb_data:
